# Generated by Django 5.1.7 on 2025-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_payment_order_id_alter_payment_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
