# Generated by Django 5.1.7 on 2025-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_couponcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='course',
            new_name='Course',
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
