# Generated by Django 5.1.7 on 2025-04-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_course_couponcode_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='date',
            new_name='enrolled_date',
        ),
        migrations.DeleteModel(
            name='CouponCode',
        ),
    ]
