# Generated by Django 5.1.7 on 2025-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_date_usercourse_enrolled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
